log_level: 0
payments_gen_tick: 5s
broker:
  seed_brokers:
    - host-1.com
    - host-2.com
    - host-3.com
  topic: my_topic
  ca_root_cert: exapmle_caRoot.pem
  user: example_user
  pass: example_password
